# Generated by Django 5.1 on 2024-08-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='origin_country',
            field=models.CharField(default='China', max_length=100),
            preserve_default=False,
        ),
    ]
